inherit_from: .rubocop_todo.yml

require:
  - rubocop-rspec

Style/Documentation:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets
  MinSize: 1

Style/WordArray:
  EnforcedStyle: brackets
  MinSize: 1

Style/SelectByRegexp:
  Enabled: false

RSpec/SpecFilePathFormat:
  Enabled: false

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2

Naming/FileName:
  Exclude:
    - 'lib/rspec-llama.rb'
